version: '2'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - fixter-keystone-data:/data/db
    ports:
      - 27017
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - mongodb
    command: npm run dev

volumes:
  keystone-data:
